INVENTORY.CONFIG = INVENTORY.CONFIG or {}

INVENTORY.CONFIG.Rows = 5
INVENTORY.CONFIG.Columns = 5

INVENTORY.CONFIG.WeightLimit = 100
INVENTORY.CONFIG.WeightSlowRate = 50 -- in percent
INVENTORY.CONFIG.ArmorRepairCost = 100


INVENTORY.CONFIG.JobSpecificItems = {
    ["Test Foundation"] = {"foundation_armor"}
}

-- Need to equal 100
INVENTORY.CONFIG.ArmorSplit = {
    ["helmet"] = 10,
    ["chest"] = 60,
    ["pants"] = 20,
    ["boots"] = 10
}

--[[
    Current wepTypes:
    "rifle"
    "smg"
    "lmg"
    "shotgun"
    "sniper"
    "dmr"
    "pistol"
    "explosive"
]]
INVENTORY.CONFIG.WeaponSpecifics = {
    ["cw_ghosts_hb"] = {wepPos = "primary", wepType = "rifle"},
    ["cw_aksd"] = {wepPos = "primary", wepType = "rifle"},
    ["cw_rinic_ar57"] = {wepPos = "primary", wepType = "rifle"},
    ["cw_auga1"] = {wepPos = "primary", wepType = "rifle"},
    ["cw_blops_famas"] = {wepPos = "primary", wepType = "rifle"},
    ["cw_soar"] = {wepPos = "primary", wepType = "rifle"},
    ["cw_fnf2000_mw2"] = {wepPos = "primary", wepType = "rifle"},
    ["cw_rinic_galil"] = {wepPos = "primary", wepType = "rifle"},
    ["cw_kac_pdw"] = {wepPos = "primary", wepType = "rifle"},
    ["cw_l85a1"] = {wepPos = "primary", wepType = "rifle"},
    ["cw_rinic_m4a1"] = {wepPos = "primary", wepType = "rifle"},
    ["cw_sako95"] = {wepPos = "primary", wepType = "rifle"},
    ["cw_sig_chan"] = {wepPos = "primary", wepType = "rifle"},
    ["cw_ak12u"] = {wepPos = "primary", wepType = "rifle"},
    ["cw_pd2_ak17"] = {wepPos = "primary", wepType = "rifle"},
    ["cw_cm901"] = {wepPos = "primary", wepType = "rifle"},
    ["cw_fad"] = {wepPos = "primary", wepType = "rifle"},
    ["cw_galil_ace"] = {wepPos = "primary", wepType = "rifle"},
    ["cw_ins_mk18"] = {wepPos = "primary", wepType = "rifle"},
    ["cw_noobveske_diplomat"] = {wepPos = "primary", wepType = "rifle"},
    ["cw_ots14"] = {wepPos = "primary", wepType = "rifle"},
    ["cw_qbz95"] = {wepPos = "primary", wepType = "rifle"},
    ["cw_rk62m"] = {wepPos = "primary", wepType = "rifle"},
    ["cw_vhs-k21"] = {wepPos = "primary", wepType = "rifle"},
    ["khr_aek971"] = {wepPos = "primary", wepType = "rifle"},
    ["khr_ak103"] = {wepPos = "primary", wepType = "rifle"},
    ["khr_cz858"] = {wepPos = "primary", wepType = "rifle"},
    ["khr_fnfal"] = {wepPos = "primary", wepType = "rifle"},
    ["khr_hcar"] = {wepPos = "primary", wepType = "rifle"},
    ["khr_m4a4"] = {wepPos = "primary", wepType = "rifle"},
    ["cw_acr"] = {wepPos = "primary", wepType = "rifle"},
    ["cw_ak74"] = {wepPos = "primary", wepType = "rifle"},
    ["cw_akm_official"] = {wepPos = "primary", wepType = "rifle"},
    ["cw_ar15"] = {wepPos = "primary", wepType = "rifle"},
    ["cw_tr09_mk18"] = {wepPos = "primary", wepType = "rifle"},
    ["cw_famasg2_official"] = {wepPos = "primary", wepType = "rifle"},
    ["cw_scarh"] = {wepPos = "primary", wepType = "rifle"},
    ["cw_g3a3"] = {wepPos = "primary", wepType = "rifle"},
    ["cw_hk416"] = {wepPos = "primary", wepType = "rifle"},
    ["cw_kk_hk416"] = {wepPos = "primary", wepType = "rifle"},
    ["cw_tr09_tar21"] = {wepPos = "primary", wepType = "rifle"},
    ["cw_l85a2"] = {wepPos = "primary", wepType = "rifle"},
    ["cw_tr09_qbz97"] = {wepPos = "primary", wepType = "rifle"},
    ["cw_tr09_auga3"] = {wepPos = "primary", wepType = "rifle"},
    ["cw_swat556"] = {wepPos = "primary", wepType = "rifle"},
    ["cw_vss"] = {wepPos = "primary", wepType = "rifle"},
    ["cw_magpul_pdr"] = {wepPos = "primary", wepType = "smg"},
    ["cw_pm9"] = {wepPos = "primary", wepType = "smg"},
    ["cw_blops_mp5"] = {wepPos = "primary", wepType = "smg"},
    ["cw_mp7mw3"] = {wepPos = "primary", wepType = "smg"},
    ["cw_tactical_thompson"] = {wepPos = "primary", wepType = "smg"},
    ["cw_vector_k10"] = {wepPos = "primary", wepType = "smg"},
    ["cw_mpl"] = {wepPos = "primary", wepType = "smg"},
    ["cw_g36c"] = {wepPos = "primary", wepType = "smg"},
    ["cw_ump45"] = {wepPos = "primary", wepType = "smg"},
    ["cw_mp5"] = {wepPos = "primary", wepType = "smg"},
    ["cw_mp7_official"] = {wepPos = "primary", wepType = "smg"},
    ["cw_m1928a1"] = {wepPos = "primary", wepType = "smg"},
    ["cw_mac11"] = {wepPos = "primary", wepType = "smg"},
    ["cw_mp40"] = {wepPos = "primary", wepType = "smg"},
    ["cw_mw2_m240"] = {wepPos = "primary", wepType = "smg"},
    ["cw_ghosts_m27iar"] = {wepPos = "primary", wepType = "lmg"},
    ["cw_rpd"] = {wepPos = "primary", wepType = "lmg"},
    ["cw_m1919a6"] = {wepPos = "primary", wepType = "lmg"},
    ["cw_m249_official"] = {wepPos = "primary", wepType = "lmg"},
    ["cw_rinic_1887"] = {wepPos = "primary", wepType = "shotgun"},
    ["cw_rinic_spas12"] = {wepPos = "primary", wepType = "shotgun"},
    ["cw_shorty"] = {wepPos = "primary", wepType = "shotgun"},
    ["cw_m98b_rinic"] = {wepPos = "primary", wepType = "sniper"},
    ["cw_ghosts_l115a3 "] = {wepPos = "primary", wepType = "sniper"},
    ["cw_sinon_pgm "] = {wepPos = "primary", wepType = "sniper"},
    ["cw_rem_m24"] = {wepPos = "primary", wepType = "sniper"},
    ["khr_m98b"] = {wepPos = "primary", wepType = "sniper"},
    ["khr_delisle"] = {wepPos = "primary", wepType = "sniper"},
    ["khr_m95"] = {wepPos = "primary", wepType = "sniper"},
    ["khr_mosin"] = {wepPos = "primary", wepType = "sniper"},
    ["khr_t5000"] = {wepPos = "primary", wepType = "sniper"},
    ["cw_k98k"] = {wepPos = "primary", wepType = "sniper"},
    ["cw_l115"] = {wepPos = "primary", wepType = "sniper"},
    ["cw_b196"] = {wepPos = "primary", wepType = "sniper"},
    ["cw_enfield"] = {wepPos = "primary", wepType = "sniper"},
    ["cw_m14"] = {wepPos = "primary", wepType = "dmr"},
    ["cw_m1garand"] = {wepPos = "primary", wepType = "dmr"},
    ["khr_simsks"] = {wepPos = "primary", wepType = "dmr"},
    ["khr_sks"] = {wepPos = "primary", wepType = "dmr"},
    ["khr_sr338"] = {wepPos = "primary", wepType = "dmr"},
    ["khr_svt40"] = {wepPos = "primary", wepType = "dmr"},
    ["khr_m1carbine"] = {wepPos = "primary", wepType = "dmr"},
    ["cw_rsass"] = {wepPos = "primary", wepType = "dmr"},
    ["cw_blops_psg1"] = {wepPos = "primary", wepType = "dmr"},
    ["cw_ichi_yon"] = {wepPos = "primary", wepType = "dmr"},
    ["cw_rinic_fnfal"] = {wepPos = "primary", wepType = "dmr"},
    ["cw_hk_sl8"] = {wepPos = "primary", wepType = "dmr"},
    ["cw_93r"] = {wepPos = "secondary", wepType = "pistol"},
    ["cw_blops_fiveseven"] = {wepPos = "secondary", wepType = "pistol"},
    ["cw_hell_glock"] = {wepPos = "secondary", wepType = "pistol"},
    ["cw_vp70"] = {wepPos = "secondary", wepType = "pistol"},
    ["cw_cod4_1911"] = {wepPos = "secondary", wepType = "pistol"},
    ["cw_ghots_m9a1"] = {wepPos = "secondary", wepType = "pistol"},
    ["cw_ghosts_p226"] = {wepPos = "secondary", wepType = "pistol"},
    ["cw_blops_python"] = {wepPos = "secondary", wepType = "pistol"},
    ["cw_rinic_glock"] = {wepPos = "secondary", wepType = "pistol"},
    ["cw_james_p99"] = {wepPos = "secondary", wepType = "pistol"},
    ["cw_fiveseven"] = {wepPos = "secondary", wepType = "pistol"},
    ["cw_m1911"] = {wepPos = "secondary", wepType = "pistol"},
    ["cw_mr96"] = {wepPos = "secondary", wepType = "pistol"},
    ["cw_p99"] = {wepPos = "secondary", wepType = "pistol"},
    ["cw_makarov"] = {wepPos = "secondary", wepType = "pistol"},
    ["cw_deagle"] = {wepPos = "secondary", wepType = "pistol"},
    ["cw_sc92fs"] = {wepPos = "secondary", wepType = "pistol"},
    ["cw_mw2_at4"] = {wepPos = "belt", wepType = "explosive"},
    ["cw_bo1_china_lake"] = {wepPos = "belt", wepType = "explosive"},
    ["cw_bo1_m72_law"] = {wepPos = "belt", wepType = "explosive"},
    ["cw_mw2_m79"] = {wepPos = "belt", wepType = "explosive"},
    ["cw_flash_grenade"] = {wepPos = "belt", wepType = "explosive"},
    ["cw_frag_grenade"] = {wepPos = "belt", wepType = "explosive"},
    ["wos_keypad_cracker"] = {wepPos = "belt", wepType = "utility"},
    ["weapon_defibrillator"] = {wepPos = "secondary", wepType = "utility"},
    ["fas2_ifak"] = {wepPos = "belt", wepType = "utility"},
    ["deployable_shield"]  = {wepPos = "secondary", wepType = "utility"},
    ["heavy_shield"]  = {wepPos = "secondary", wepType = "utility"},
    ["riot_shield"]  = {wepPos = "secondary", wepType = "utility"},
    ["m9k_ied_detonator"] = {wepPos = "belt", wepType = "explosive"},
    ["m9k_suicide_bomb"] = {wepPos = "belt", wepType = "explosive"},
    ["au_ds_wrench"] = {wepPos = "belt", wepType = "utility"},
    ["stungun"] = {wepPos = "belt", wepType = "utility"},
    ["cw_smoke_grenade"] = {wepPos = "belt", wepType = "explosive"},
    ["swt_cloakingmodule"] = {wepPos = "belt", wepType = "utility"},
    ["m9k_m61_frag"] = {wepPos = "belt", wepType = "explosive"},
    ["m9k_sticky_grenade"] = {wepPos = "belt", wepType = "explosive"},
    ["weapon_extinguisher"] = {wepPos = "belt", wepType = "utility"},
    ["weapon_extinguisher_infinite"] = {wepPos = "belt", wepType = "utility"},
}

-- Sweps that won't be counted as inventory items when spawned.
INVENTORY.CONFIG.DenyListSweps = {
    ["weapon_empty_hands"] = true,
    ["weapon_physgun"] = true,
    ["weapon_physcannon"] = true,
    ["gmod_tool"] = true,
    ["weapon_keypadchecker"] = true,
    ["arrest_stick"] = true,
    ["door_ram"] = true,
    ["keys"] = true,
    ["lockpick"] = true,
    ["med_kit"] = true,
    ["pocket"] = true,
    ["stunstick"] = true,
    ["unarrest_stick"] = true,
    ["weaponchecker"] = true,
    ["weapon_fists"] = true,
    ["manhack_welder"] = true,
    ["gmod_camera"] = true,
    ["scp_662"] = true,
    ["atlas_scp_682"] = true,
    ["eoti_zombie_swep"] = true,
    ["scp_049_scp"] = true,
    ["weapon_scp096"] = true,
    ["weapon_scp106swep"] = true,
    ["eoti_werewolf_swep"] = true,
    ["weapon_scp457"] = true,
    ["eoti_raven_swep"] = true,
    ["weapon_scp939swep"] = true,
    ["weapon_scp999"] = true,
    ["au_scp_066"] = true,
    ["scp-076-2"] = true,
    ["au_scp096_swep"] = true,
    ["scprp_weapon_scp_1048a"] = true,
    ["scp_174_atl"] = true,
    ["scp-4000-w"] = true,
    ["weapon_scp420_atl"] = true,
    ["weapon_662"] = true,
    ["scp_6750"] = true,
    ["fv_scp682"] = true,
    ["au_scp_682"] = true,
    ["scp_8602"] = true,
    ["zombie_claws"] = true,
    ["weapon_keycard_level1"] = true,
    ["weapon_keycard_level2"] = true,
    ["weapon_keycard_level3"] = true,
    ["weapon_keycard_level4"] = true,
    ["weapon_keycard_level5"] = true,
    ["weapon_keycard_omni"] = true,
    ["wos_keycard_base"] = true,
    ["wos_kcs_placer"] = true,
    ["wos_scp_keyplacer"] = true,
    ["au_bomb_collar"] = true,
    ["weapon_cuff_elastic"] = true,
    ["au_held_depot_crate"] = true,
    ["au_held_hub_crate"] = true,
    ["weapon_handcuffed"] = true,
    ["weapon_cuff_base"] = true,
    ["sonido_swep"] = true,
    ["weapon_katana"] = true,
    ["swep-457"] = true,
    ["weapon_nessbat(normal)"] = true,
    ["eoti_werewolf_swep"] = true,
    ["minimize"] = true,
    ["au_shield"] = true,
    ["au_966_new"] = true,
    ["scp_662"] = true,
    ["atlas_scp_106"] = true,
    ["weapon_scp1048_a"] = true,
    ["weapon_scp1048"] = true,
    ["weapon_rpt_cuffed"] = true,
    ["weapon_rpt_handcuff"] = true,
    ["weapon_rpt_surrender"] = true,
    ["weapon_adv_keys_2"] = true,
    ["au_ping_collar"] = true,
    ["au_amnestic_a"] = true,
    ["au_amnestic_b"] = true,
    ["au_amnestic_c"] = true,
    ["au_amnestic_d"] = true,
    ["au_amnestic_e"] = true,
    ["au_amnestic_f"] = true,
    ["au_amnestic_g"] = true,
    ["au_amnestic_h"] = true,
    ["au_amnestic_i"] = true,
    ["au_amnestic_w"] = true,
    ["au_amnestic_x"] = true,
    ["au_amnestic_y"] = true,
    ["au_amnestic_z"] = true,
    ["elixir_extractor"] = true,
    ["realistic_hook"] = true,
    ["cross_arms_infront_swep"] = true,
    ["weapon_armorkit"] = true,
    ["scp_035_swep"] = true,
    ["mvp_perfecthands"] = true,
}